version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin12345
      POSTGRES_USER: postgres
      POSTGRES_DB: test_task
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin12345
      POSTGRES_DATABASE: test_task
      IS_PROD: "true"
      SECRET_KEY: secretsecretsecret
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
